name: Trigger garden build

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger gardden
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.TRIGGER_GARDEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/dovonun/garden/dispatches \
            -d '{"event_type": "trigger-action"}'